apiVersion: apps/v1

kind: Deployment

metadata:

  name: mhc-back
  labels:
    app: mhc-back
spec:

  replicas: 1
  selector:
    matchLabels:
      app: mhc-back
  template:

    metadata:

      labels:

        app: mhc-back

    spec:

      containers:

      - name: mhc-back

        image: mcr.microsoft.com/mssql/server

        ports:

        - containerPort: 1433

          name: redis

---

apiVersion: v1

kind: Service

metadata:

  name: mhc-back

spec:
  type: ClusterIP
  ports:

  - port: 1433

  selector:

    app: mhc-back

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: mhc-front

spec:

  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 1

  minReadySeconds: 5 
  selector:
    matchLabels:
      app: mhc-front
  template:

    metadata:

      labels:

        app: mhc-front

    spec:

      containers:

      - name: mhc-front

        image: __ACR__/StudentPortal.Web:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 8080

        resources:

          requests:

            cpu: 250m

          limits:

            cpu: 500m

        env:

        - name: REDIS

          value: "mhc-back"

---

apiVersion: v1

kind: Service

metadata:

  name: mhc-front

spec:

  type: LoadBalancer

  ports:

  - port: 8080

  selector:
    app: mhc-front